#!/bin/bash

# BASE VERSION - Begin
BASE_VERSION=0.01
# BASE VERSION - End

# SUFFIX VERSION - Begin
SUFFIX_VERSION=""
# SUFFIX VERSION - End

#PACKAGE VERSION - Begin
PACKAGE_VERSION=${BASE_VERSION}${SUFFIX_VERSION}
#PACKAGE VERSION - End

usage() {
cat <<EOF

  zmsetup ${PACKAGE_VERSION}
  Copyright Adrian Gibanel Lopez
  Licensed under the GNU PUBLIC LICENSE 3.0

  Usage: $0 [--conf=CONFIGURATION_FILE] [--install-needed-packages] [--distro=DISTRIBUTION] [--split-dns-bind]

  Example: $0 --conf=/home/user/myzimbra.conf

  INSTALL NEEDED PACKAGES
  =======================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --install-needed-packages --distro=ubuntu1204
  Config file example:
    DISTRO="ubuntu1204"
    INSTALL_NEED_PACKAGES="yes"
    
  SPLIT DNS BIND SETUP
  ====================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --split-dns-bind --distro=ubuntu1204
  Config file example:
    DISTRO="ubuntu1204"
    SPLIT_DNS_BIND_SETUP="yes"

  DOWNLOAD ZCS
  ============
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --download-zcs --distro=ubuntu1204 --zimbra-type=ose --specific-download=807
  Config file example:
    DISTRO="ubuntu1204"
    DOWNLOAD_ZCS="yes"
    ZIMBRA_TYPE="ose"
    SPECIFIC_DOWNLOAD="807"

  INSTALL_ZCS_LDAP
  ================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --install-zcs-ldap
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    INSTALL_ZCS_LDAP="yes"

  INSTALL_ZCS_PROXY
  =================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --install-zcs-proxy
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    INSTALL_ZCS_PROXY="yes"

  NAGIOS_ZCS_LDAP
  ================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --nagios-zcs-ldap
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    NAGIOS_ZCS_LDAP="yes"

  INSTALL_ZCS_MTA
  ================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --install-zcs-mta
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    INSTALL_ZCS_MTA="yes"

  NAGIOS_ZCS_MTA
  ================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --nagios-zcs-mta
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    NAGIOS_ZCS_MTA="yes"

  SETUP_ZCS_MTA_PLUS
  ==================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --setup-zcs-mta-plus
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    SETUP_ZCS_MTA_PLUS="yes"

  REENABLE_ZCS_MTA_PLUS
  ==================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --reenable-zcs-mta-plus
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    REENABLE_ZCS_MTA_PLUS="yes"

  SETUP_ZCS_MTA_MULTIPLE_IPS
  ==========================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --setup-zcs-multiple-ips
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    SETUP_ZCS_MTA_MULTIPLE_IPS="yes"
    MTA_MULTIPLE_IP_DOMAIN[0]="domain1.com"
    MTA_MULTIPLE_IP_ADDRESS[0]="1.2.3.4"
    MTA_MULTIPLE_IP_VIRTUALHOST[0]="mail.domain1.com"
    MTA_MULTIPLE_IP_DOMAIN[1]="domain2.com"
    MTA_MULTIPLE_IP_ADDRESS[1]="3.5.7.9"
    MTA_MULTIPLE_IP_VIRTUALHOST[1]="webmail.domain2.com"

  DISABLE_ENCRYPTED_PDF_WARNING
  =============================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --disable-encrypted-pdf-warning
  Config file example:
    DISABLE_ENCRYPTED_PDF_WARNING="yes"

  INSTALL_ZCS_MAILBOX
  ===================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --install-zcs-mailbox --keep-custom-zimlets --keep-custom-skins
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    INSTALL_ZCS_MAILBOX="yes"
    KEEP_CUSTOM_ZIMLETS="yes"
    KEEP_CUSTOM_SKINS="yes"

  NAGIOS_ZCS_MAILBOX
  ==================
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --nagios-zcs-mailbox
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    NAGIOS_ZCS_MAILBOX="yes"

  SETUP_CATALA
  ============
  Command line example:
    Example: $0 --conf=/home/user/myzimbra.conf --distro=ubuntu1204 --zimbra-type=ose --multi-spell-catala --spell-catala --language-catala
  Config file example:
    DISTRO="ubuntu1204"
    ZIMBRA_TYPE="ose"
    INSTALL_ZCS_MAILBOX="yes"
    MULTI_SPELL_CATALA="yes"
    SPELL_CATALA="yes"
    LANGUAGE_CATALA="yes"

EOF

}

# Creates a sed partial string for substitution
# $1 is the FROM string
# $2 is the TO string
sed_partial_string()
{
	#local FILE="$1"
	local FROM="$1"
	local TO="$2"

echo "s~$FROM~$TO~g"

} # End of sed_partial_string()

function check_executable_file () {

    local PARAMETRES_NUMBER=1

    if [[ ! $# -eq ${PARAMETRES_NUMBER} ]]
    then
    echo -e -n "Incorrect number of parametres (check_executable_file)\n"
    echo -e -n "Aborting...\n"
    exit 1;
    fi

  local FILE_TO_CHECK=$1;

  if [[ ! -x ${FILE_TO_CHECK} ]]
  then
  echo -e -n "Required file: ${FILE_TO_CHECK} (executable) was not found\n"
  echo -e -n "Aborting...\n"
  exit 1;
  fi  


}


function check_exists_file () {

    local PARAMETRES_NUMBER=1

    if [[ ! $# -eq ${PARAMETRES_NUMBER} ]]
    then
    echo -e -n "Incorrect number of parametres (check_exists_file)\n"
    echo -e -n "Aborting...\n"
    exit 1;
    fi

  local FILE_TO_CHECK=$1;

  if [[ ! -e ${FILE_TO_CHECK} ]]
  then
  echo -e -n "Required file: ${FILE_TO_CHECK} (exists) was not found\n"
  echo -e -n "Aborting...\n"
  exit 1;
  fi  


}
 
### MAIN PROGRAM ### ### ### ### ### ### ### ###
################ ### ### ### ### ### ### ### ###
###              ### ### ### ### ### ### ### ###
###              ### ### ### ### ### ### ### ###

# Check the arguments.
for option in "$@"; do
    case "$option" in
    -h | --help)
	usage
	exit 0 ;;
    -v | --version)
	echo "zmsetup (${PACKAGE_VERSION})"
	exit 0 ;;
    --distro=*)
	DISTRO=`echo "$option" | sed 's/--distro=//'` ;;
    --conf=*)
	CONF=`echo "$option" | sed 's/--conf=//'` ;;
    --install-needed-packages )
	INSTALL_NEED_PACKAGES="yes" ;;
    # This is an undocumented feature...
    --debug)
	debug=yes ;;
    -*)
	echo "Unrecognized option \`$option'" 1>&2
	usage
	exit 1
	;;
    *)
	echo "Unrecognized option \`$option'" 1>&2
	usage
	exit 1
	;;
    esac
done

ZMSETUP_DEFAULT_CONF_FILE="/usr/local/etc/zmsetup/default.conf"
ZMSETUP_DEFAULT_CONFD="/usr/local/etc/zmsetup/conf.d/"
ZMSETUP_DEFAULT_LIB_DIR="/usr/local/lib/zmsetup"

# Read default custom file for this host

if [ -f "${ZMSETUP_DEFAULT_CONF_FILE}" ] ; then
  source "${ZMSETUP_DEFAULT_CONF_FILE}"
fi

# Read custom configuration files for this host
# if they exist
if [ -d "${ZMSETUP_DEFAULT_CONFD}" ] ; then
  source "${ZMSETUP_DEFAULT_CONFD}"/*\.conf
fi

# If a custom file is specified check if we can read it or abort
if [[ "x${CONF}" != x ]] ; then
  if [ ! -f "${CONF}" ] ; then
    echo -e -n "We cannot read configuration file: ${CONF}\n"
    echo -e -n "Aborting...\n"
    exit 1
  else
    source "${CONF}"
  fi
fi

# Check if lib dir exists and its common.sh file
if [ ! -f "${ZMSETUP_DEFAULT_LIB_DIR}"/"common.sh" ] ; then
  echo -e -n "We cannot read common.sh file: ${ZMSETUP_DEFAULT_LIB_DIR}/common.sh \n"
  echo -e -n "Check your zmsetup installation\n"
  echo -e -n "Aborting...\n"
  exit 1
else
  source "${ZMSETUP_DEFAULT_LIB_DIR}"/"common.sh"
fi

